import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import Navbar from "@/component/Navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="w-full px-4 sm:px-8 py-4 sm:py-8 min-h-screen">
                    <div className="w-full border-4 border-[#3A994C] rounded-4xl pt-4 pb-8 px-4 min-h-[calc(100vh-2rem)] sm:min-h-[calc(100vh-4rem)]">
                        <TRPCReactProvider>
                            <Navbar />
                            <div className="mt-4">
                                {children}
                            </div>
                        </TRPCReactProvider>
                    </div>
                </div>
            </body>
        </html>
    );
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { TRPCReactProvider } from "@/trpc/client";
// import Navbar from "@/component/Navbar";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };

// export default function RootLayout({
//     children,
// }: Readonly<{
//     children: React.ReactNode;
// }>) {
//     return (
//         <html lang="en">
//             <body
//                 className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
//             >
//                 <div className="w-full h-screen px-4 sm:px-8 py-4 sm:py-8">
//                     <div className="w-full h-full border-4 border-[#3A994C] rounded-4xl flex flex-col">
//                         <TRPCReactProvider>
//                             {/* Fixed Navbar */}
//                             <div className="pt-4 px-4 flex-shrink-0">
//                                 <Navbar />
//                             </div>
                            
//                             {/* Scrollable Content Area */}
//                             <div className="flex-1 overflow-y-auto px-4 pb-8 mt-4">
//                                 {children}
//                             </div>
//                         </TRPCReactProvider>
//                     </div>
//                 </div>
//             </body>
//         </html>
//     );
// }
