import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TRPCReactProvider } from "@/trpc/client";
import Navbar from "@/component/Navbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full">
            <body
                className={`h-full ${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="h-full w-full px-8 py-8">
                    <div className="h-full w-full border-4 border-[#3A994C] rounded-4xl pt-4 pb-8 px-4 flex flex-col">
                        <TRPCReactProvider>
                            <Navbar />
                            <div className="flex-1">
                                {children}
                            </div>
                        </TRPCReactProvider>
                    </div>
                </div>
            </body>
        </html>
    );
}
